### ISSUE TITLE
Ability to trigger alarm siren

### ISSUE THREAD

**Issue by zx8** [maciej-or/hikvision_next#114]
Thanks to https://community.home-assistant.io/t/hikvision-cameras-trigger-audio-alarm-output-possible/545886/5, I learned that it is possible to trigger the alarm output on a camera with:

```yaml
rest_command:
  drive_audio:
    url: "http://CAMERAIPADDRESS/ISAPI/Event/triggers/notifications/AudioAlarm/14/test?format=json"    
    username: ********
    password: ********
    method: put
```

I tried this myself and it did in fact trigger the alarm siren for around 5 seconds, and then the siren automatically turned itself off.

Would it be possible to integrate this so we can have a neat way of triggering the siren without having to resort to using `rest_command`?

Thank you!
