### ISSUE TITLE
Feature Request: Switch for the white ColorVU LED on cameras

### ISSUE THREAD

**Issue by nagyrobi** [maciej-or/hikvision_next#16]
Currently I implement switches for the LEDs of these cameras using this method:
https://github.com/nagyrobi/home-assistant-configuration-examples/tree/main/hikvision_colorvu_led_switch
It relies on ISAPI, using with CURL.

**Comment by nagyrobi** [comment]
Also additionally it's possible to make the automatic turn on and off of those leds based on the sunset and sunrise from HA, with something like:

```
curl -k --silent -H "Content-Type:application/xml" -X PUT -d "<ExternalDevice><SupplementLight><mode>schedule</mode><Schedule><TimeRange><beginTime>{{states('sensor.camera_led_on')}}</beginTime><endTime>{{states('sensor.camera_led_off')}}</endTime></TimeRange></Schedule></SupplementLight></ExternalDevice>" http://ip.address/ISAPI/System/externalDevice --digest -u user:pass

curl -k --silent -H 'Content-Type:application/xml' -X PUT -d '<ISPMode><mode>schedule</mode><Schedule><scheduleType>day</scheduleType><TimeRange><beginTime>{{states('sensor.camera_led_off')}}</beginTime><endTime>{{states('sensor.camera_led_on')}}</endTime></TimeRange></Schedule></ISPMode>' http://ip.address/ISAPI/Image/channels/1/ISPMode --digest -u user:pass
```

Where `sensor.camera_led_on` and `sensor.camera_led_off` are sunset and sunrise times properly formatted for ISAPI

```yaml
- platform: template
  sensors:
    camera_led_on:
      friendly_name: 'Cameras turn LEDs ON time'
      unique_id: camera_led_on
      value_template: >
        {{ (as_timestamp(states.sun.sun.attributes.next_setting) + 900 ) | timestamp_custom('%H:%M:%S') }}
      icon_template: mdi:lighthouse-on
    camera_led_off:
      friendly_name: 'Cameras turn LEDs OFF time'
      unique_id: camera_led_off
      value_template: >
        {{ (as_timestamp(states.sun.sun.attributes.next_rising) - 900 ) | timestamp_custom('%H:%M:%S') }}
      icon_template: mdi:lighthouse
```

**Comment by maciej-or** [comment]
I agree, but for adding binary sensor I need info if camera has LED feature. Could you send me your camera responses for these ISAPI endpoints?
{camera_ip}/ISAPI/System/deviceInfo
{camera_ip}/ISAPI/Event/capabilities
{camera_ip}ISAPI/Smart/capabilities

**Comment by nagyrobi** [comment]
{camera_ip}/ISAPI/System/deviceInfo:
```xml
<DeviceInfo version="2.0">
<deviceName>Name</deviceName>
<deviceID>redacted</deviceID>
<deviceDescription>IPCamera</deviceDescription>
<deviceLocation>hangzhou</deviceLocation>
<systemContact>Hikvision.China</systemContact>
<model>DS-2CD2T47G1-L</model>
<serialNumber>DS-2CD2T47G1-redacted</serialNumber>
<macAddress>redacted</macAddress>
<firmwareVersion>V5.6.820</firmwareVersion>
<firmwareReleasedDate>build 220519</firmwareReleasedDate>
<encoderVersion>V7.3</encoderVersion>
<encoderReleasedDate>build 220307</encoderReleasedDate>
<bootVersion>V1.3.4</bootVersion>
<bootReleasedDate>100316</bootReleasedDate>
<hardwareVersion>0x0</hardwareVersion>
<deviceType>IPCamera</deviceType>
<telecontrolID>11</telecontrolID>
<supportBeep>false</supportBeep>
<supportVideoLoss>false</supportVideoLoss>
<firmwareVersionInfo>B-R-G1-0</firmwareVersionInfo>
</DeviceInfo>
```

{camera_ip}/ISAPI/Event/capabilities:
```xml
<EventCap version="2.0">
<isSupportHDFull>true</isSupportHDFull>
<isSupportHDError>true</isSupportHDError>
<isSupportNicBroken>true</isSupportNicBroken>
<isSupportIpConflict>true</isSupportIpConflict>
<isSupportIllAccess>true</isSupportIllAccess>
<isSupportViException>false</isSupportViException>
<isSupportViMismatch>false</isSupportViMismatch>
<isSupportRecordException>false</isSupportRecordException>
<isSupportTriggerFocus>false</isSupportTriggerFocus>
<isSupportMotionDetection>true</isSupportMotionDetection>
<isSupportVideoLoss>false</isSupportVideoLoss>
<isSupportTamperDetection>true</isSupportTamperDetection>
<isSupportPersonQueueDetection>false</isSupportPersonQueueDetection>
<isSupportTeacherBehaviorDetect>false</isSupportTeacherBehaviorDetect>
<isSupportFaceSnap>false</isSupportFaceSnap>
<isSupportCityManagement>false</isSupportCityManagement>
<isSupportMixedTargetDetection>false</isSupportMixedTargetDetection>
</EventCap>
```

{camera_ip}/ISAPI/Smart/capabilities:
```xml
<SmartCap version="2.0">
<isSupportROI>true</isSupportROI>
<isSupportFaceDetect>true</isSupportFaceDetect>
<isSupportIntelliTrace>false</isSupportIntelliTrace>
<isSupportFieldDetection>true</isSupportFieldDetection>
<isSupportDefocusDetection>false</isSupportDefocusDetection>
<isSupportAudioDetection>false</isSupportAudioDetection>
<isSupportSceneChangeDetection>true</isSupportSceneChangeDetection>
<isSupportLineDetection>true</isSupportLineDetection>
<isSupportRegionEntrance>false</isSupportRegionEntrance>
<isSupportRegionExiting>false</isSupportRegionExiting>
<isSupportLoitering>false</isSupportLoitering>
<isSupportGroup>false</isSupportGroup>
<isSupportRapidMove>false</isSupportRapidMove>
<isSupportParking>false</isSupportParking>
<isSupportUnattendedBaggage>true</isSupportUnattendedBaggage>
<isSupportAttendedBaggage>true</isSupportAttendedBaggage>
<isSupportPeopleDetection>false</isSupportPeopleDetection>
<isSupportSmartCalibration>true</isSupportSmartCalibration>
<isSupportStorageDetection>false</isSupportStorageDetection>
</SmartCap>
```

**Comment by nagyrobi** [comment]
I think you should look for the presence of `<ExternalDevice><SupplementLight>` in `/ISAPI/System/externalDevice`:
```xml
<ExternalDevice version="2.0">
<SupplementLight>
<enabled>true</enabled>
<brightnessRegulateMode>manual</brightnessRegulateMode>
<mode>schedule</mode>
<Schedule>
<TimeRange>
<beginTime>19:46:18</beginTime>
<endTime>05:40:26</endTime>
</TimeRange>
</Schedule>
<brightness>1</brightness>
<maxBrightness>50</maxBrightness>
</SupplementLight>
</ExternalDevice>
```

**Comment by amzaldua** [comment]
The following code works for me (DS-2CD2047G2-LU/SL):
```
command_line:
  - switch:
      name: supplementlight_camera_03
      command_on: "curl -k --silent -H 'Content-Type:application/xml' -X PUT -d '<SupplementLight><supplementLightMode>colorVuWhiteLight</supplementLightMode><mixedLightBrightnessRegulatMode>auto</mixedLightBrightnessRegulatMode><whiteLightBrightness>100</whiteLightBrightness></SupplementLight>' http://IP_Camera_03/ISAPI/Image/channels/1/supplementLight --digest -u user:password"
      command_off: "curl -k --silent -H 'Content-Type:application/xml' -X PUT -d '<SupplementLight><supplementLightMode>colorVuWhiteLight</supplementLightMode><mixedLightBrightnessRegulatMode>auto</mixedLightBrightnessRegulatMode><whiteLightBrightness>0</whiteLightBrightness></SupplementLight>' http://IP_Camera_03/ISAPI/Image/channels/1/supplementLight --digest -u user:password"
  - switch:
      name: supplementlight_camera_02
      command_on: "curl -k --silent -H 'Content-Type:application/xml' -X PUT -d '<SupplementLight><supplementLightMode>colorVuWhiteLight</supplementLightMode><mixedLightBrightnessRegulatMode>auto</mixedLightBrightnessRegulatMode><whiteLightBrightness>100</whiteLightBrightness></SupplementLight>' http://IP_Camera_02/ISAPI/Image/channels/1/supplementLight --digest -u user:password"
      command_off: "curl -k --silent -H 'Content-Type:application/xml' -X PUT -d '<SupplementLight><supplementLightMode>colorVuWhiteLight</supplementLightMode><mixedLightBrightnessRegulatMode>auto</mixedLightBrightnessRegulatMode><whiteLightBrightness>0</whiteLightBrightness></SupplementLight>' http://IP_Camera_02/ISAPI/Image/channels/1/supplementLight --digest -u user:password"
  - switch:
      name: supplementlight_camera_01
      command_on: "curl -k --silent -H 'Content-Type:application/xml' -X PUT -d '<SupplementLight><supplementLightMode>colorVuWhiteLight</supplementLightMode><mixedLightBrightnessRegulatMode>auto</mixedLightBrightnessRegulatMode><whiteLightBrightness>100</whiteLightBrightness></SupplementLight>' http://IP_Camera_01/ISAPI/Image/channels/1/supplementLight --digest -u user:password"
      command_off: "curl -k --silent -H 'Content-Type:application/xml' -X PUT -d '<SupplementLight><supplementLightMode>colorVuWhiteLight</supplementLightMode><mixedLightBrightnessRegulatMode>auto</mixedLightBrightnessRegulatMode><whiteLightBrightness>0</whiteLightBrightness></SupplementLight>' http://IP_Camera_01/ISAPI/Image/channels/1/supplementLight --digest -u user:password"
```

Is possible to do the same with the whiteLightAlarm?
