### ISSUE TITLE
Trigger alarm

### ISSUE THREAD

**Issue by kroese** [maciej-or/hikvision_next#55]
My Hikvision has speakers to make an alarm sound, is there any way this integration could expose this alarm as a binary sensor so that I can trigger it from an automation?

**Comment by REH-dev** [comment]
Mine also. I am also interested for such a feature.

**Comment by PovilasID** [comment]
Here is a shell script that should trigger a test of alarm:
```
sound_camera_alarm: >
  curl -k --silent -X PUT http://{{host}}:{{port}}/ISAPI/Event/triggers/notifications/AudioAlarm/1/test?format=json  --digest -u {{username}}:{{password}}
```
It needs an automation to trigger:
```
alias: Door camera alarm sounding
description: ""
trigger:
  - platform: state
    entity_id:
      - input_button.door_camera_alarm
condition: []
action:
  - service: shell_command.sound_camera_alarm
    data_template:
      host: !secret door_camera_host
      port: !secret door_camera_port
      username: !secret door_camera_username
      password: !secret door_camera_password
mode: single
```
* There needs to be a helper button created named door_camera_alarm 
To test you can replace secret calls with just data  and default port is 80
It runs only for 5 sec by default but you can set the test duration to be logner
